about:
  home: https://github.com/hsiaoyi0504/conda_gromacs_4.5.5
  license: MIT License
  summary: GROMACS (http://www.gromacs.org/) is a versatile package to perform molecular dynamics. I created this to make people more easy incorporate old gromacs into applications.

package:
  name: gromacs
  version: 4.5.5

build:
  number: 0

source:
  fn: gromacs-4.5.5.tar.gz
  url: ftp://ftp.gromacs.org/pub/gromacs/gromacs-4.5.5.tar.gz
  md5: 6a87e7cdfb25d81afa9fea073eb28468
  folder: gromacs_4.5.5/

requirements:
  build:
    - gcc_linux-64  # [linux]
    - gxx_linux-64  # [linux]
    - cmake  # [linux]
  run:
    - libgcc  # [linux]

test:
  commands:
    - mdrun -version